package Entities;
// Generated 16-oct-2017 18:50:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Formula generated by hbm2java
 */
public class Formula  implements java.io.Serializable {


     private int idFormula;
     private String nombreFormula;
     private String detalle;
     private Set<ProductoFormula> productoFormulas = new HashSet<ProductoFormula>(0);

    public Formula() {
    }

	
    public Formula(int idFormula) {
        this.idFormula = idFormula;
    }
    public Formula(int idFormula, String nombreFormula, String detalle, Set<ProductoFormula> productoFormulas) {
       this.idFormula = idFormula;
       this.nombreFormula = nombreFormula;
       this.detalle = detalle;
       this.productoFormulas = productoFormulas;
    }
   
    public int getIdFormula() {
        return this.idFormula;
    }
    
    public void setIdFormula(int idFormula) {
        this.idFormula = idFormula;
    }
    public String getNombreFormula() {
        return this.nombreFormula;
    }
    
    public void setNombreFormula(String nombreFormula) {
        this.nombreFormula = nombreFormula;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public Set<ProductoFormula> getProductoFormulas() {
        return this.productoFormulas;
    }
    
    public void setProductoFormulas(Set<ProductoFormula> productoFormulas) {
        this.productoFormulas = productoFormulas;
    }




}


