package Entities;
// Generated 16-oct-2017 18:50:52 by Hibernate Tools 4.3.1



/**
 * Indicacion generated by hbm2java
 */
public class Indicacion  implements java.io.Serializable {


     private int idIndicacion;
     private Preparacion preparacion;
     private int orden;
     private String detalle;

    public Indicacion() {
    }

    public Indicacion(int idIndicacion, Preparacion preparacion, int orden, String detalle) {
       this.idIndicacion = idIndicacion;
       this.preparacion = preparacion;
       this.orden = orden;
       this.detalle = detalle;
    }
   
    public int getIdIndicacion() {
        return this.idIndicacion;
    }
    
    public void setIdIndicacion(int idIndicacion) {
        this.idIndicacion = idIndicacion;
    }
    public Preparacion getPreparacion() {
        return this.preparacion;
    }
    
    public void setPreparacion(Preparacion preparacion) {
        this.preparacion = preparacion;
    }
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }




}


