package Entities;
// Generated 16-oct-2017 18:50:52 by Hibernate Tools 4.3.1



/**
 * ProductoFormula generated by hbm2java
 */
public class ProductoFormula  implements java.io.Serializable {


     private int idProductoFormula;
     private Formula formula;
     private Producto productoByFkIdProductoInsumo;
     private Producto productoByFkIdProductoElaborado;
     private double porcentaje;

    public ProductoFormula() {
    }

    public ProductoFormula(int idProductoFormula, Formula formula, Producto productoByFkIdProductoInsumo, Producto productoByFkIdProductoElaborado, double porcentaje) {
       this.idProductoFormula = idProductoFormula;
       this.formula = formula;
       this.productoByFkIdProductoInsumo = productoByFkIdProductoInsumo;
       this.productoByFkIdProductoElaborado = productoByFkIdProductoElaborado;
       this.porcentaje = porcentaje;
    }
   
    public int getIdProductoFormula() {
        return this.idProductoFormula;
    }
    
    public void setIdProductoFormula(int idProductoFormula) {
        this.idProductoFormula = idProductoFormula;
    }
    public Formula getFormula() {
        return this.formula;
    }
    
    public void setFormula(Formula formula) {
        this.formula = formula;
    }
    public Producto getProductoByFkIdProductoInsumo() {
        return this.productoByFkIdProductoInsumo;
    }
    
    public void setProductoByFkIdProductoInsumo(Producto productoByFkIdProductoInsumo) {
        this.productoByFkIdProductoInsumo = productoByFkIdProductoInsumo;
    }
    public Producto getProductoByFkIdProductoElaborado() {
        return this.productoByFkIdProductoElaborado;
    }
    
    public void setProductoByFkIdProductoElaborado(Producto productoByFkIdProductoElaborado) {
        this.productoByFkIdProductoElaborado = productoByFkIdProductoElaborado;
    }
    public double getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(double porcentaje) {
        this.porcentaje = porcentaje;
    }




}


